//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorium.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratorium.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функции для вычисления наибольшего общего делителя..
        /// </summary>
        public static string IAdvancedEuclideanAlgorithm {
            get {
                return ResourceManager.GetString("IAdvancedEuclideanAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алгоритм Евклида для вычисления наибольшего общего делителя..
        /// </summary>
        public static string IEuclideanAlgorithm {
            get {
                return ResourceManager.GetString("IEuclideanAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функции для вычисления наименьшего общего кратного..
        /// </summary>
        public static string ILeastCommonMultipleAlgorithm {
            get {
                return ResourceManager.GetString("ILeastCommonMultipleAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функции для определения того, является ли число квадратичным вычетом по заданному модулю или нет.  Возвращает &quot;1&quot;, когда вычет и &quot;-1&quot; - невычет..
        /// </summary>
        public static string IQuadraticResidue {
            get {
                return ResourceManager.GetString("IQuadraticResidue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тесты на простоту. Возвращают &quot;-1&quot;, когда число составное, и &quot;0&quot;, когда не удалось установить..
        /// </summary>
        public static string ITestOfSimplicity {
            get {
                return ResourceManager.GetString("ITestOfSimplicity", resourceCulture);
            }
        }
    }
}
