//Problem 2 - Even Fibonacci numbers - solved
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

let check (x:int64) = x % (int64)2 = (int64)0

let rec fiboSum (acc:int64) (a:int64) (b:int64) =
    if b < (int64)4000000
    then 
        if check b
        then fiboSum (acc + b) b (a + b)
        else fiboSum acc b (a + b)
    else acc

fiboSum ((int64)0) ((int64)1) ((int64)2);;